<?php


namespace UserBundle\Repository;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    function Searchenfant($iduser)
    {

        $query = $this->getEntityManager()->createQuery(
            "SELECT c.prenom FROM eventBundle:enfant c where c.idParent='$iduser'"
        );
        return $query->getResult();

    }

    public function UserMailR($mail)
    {
        $q=$this->getEntityManager()->createQuery(
            "Select u from UserBundle:User u where u.email='".$mail."'  "
        );
        return $q->getResult();
    }

    public function UserByUsername($usern)
    {
        $q=$this->getEntityManager()->createQuery(
            "Select u from UserBundle:User u where u.username='".$usern."'  "
        );
        return $q->getResult();
    }
}