<?php

namespace eventBundle\Repository;

/**
 * enfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class enfantRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindallEnfant(){
        $query=$this->getEntityManager()->createQuery(
            "SELECT c,d FROM eventBundle:enfant c, eventBundle:parents d  where c.parents=d.idParents"
        );
        return $query->getResult();
    }









    public function myfindallEnfantkarim(){
        $query=$this->getEntityManager()->createQuery(
            "SELECT c.nom FROM eventBundle:enfant c"
        );
        return $query->getResult();
    }
}
