<?php

namespace eventBundle\Repository;

/**
 * inscription_evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class inscription_evenementRepository extends \Doctrine\ORM\EntityRepository
{



}
