<?php

namespace PlanBundle\Repository;

/**
 * EmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiRepository extends \Doctrine\ORM\EntityRepository
{

    public function findgroupswithTT()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT DISTINCT IDENTITY(e.idGroup),g.nomGroup FROM PlanBundle:Emploi e,PlanBundle:Groupe g where g.idGroup=e.idGroup   "
            )
            ->getResult();
    }
    public function findbyId($idGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT  IDENTITY(e.idGroup) FROM PlanBundle:Emploi e where e.idGroup='$idGroup'   "
            )
            ->getResult();
    }
    public function showEmp($idGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e.idemp,e.seanceMatin,e.seanceSoir,s.nomSalle from PlanBundle:Emploi e,PlanBundle:Salles s where e.idGroup='$idGroup' AND s.numSalle=e.idSalle ORDER BY e.jour    "
            )
            ->getResult();
    }
    public function findgroupname($idGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT g.nomGroup,g.idGroup from PlanBundle:Groupe g where g.idGroup='$idGroup' "
            )
            ->getResult();
    }
    public function findgroupid($idGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT DISTINCT IDENTITY(e.idGroup) from PlanBundle:Emploi e where e.idGroup='$idGroup' "
            )
            ->getResult();
    }
    public function deleteEmp($idemp)
    {
        return $this->getEntityManager()
            ->createQuery(
                "DELETE FROM PlanBundle:Emploi e  WHERE e.idemp='$idemp' "
            )
            ->getResult();
    }
    public function Findsallemob($idGroup,$jour)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT s.nomSalle FROM PlanBundle:Salles s,PlanBundle:Emploi e WHERE e.idGroup='$idGroup' and e.jour='$jour' AND s.numSalle=e.idSalle"

            )
            ->getResult();
    }


}
