<?php

namespace PlanBundle\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByGroup($idGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e.id,e.nom,e.prenom,e.datenaiss,e.sexe FROM PlanBundle:Enfant e  where e.idGroup='$idGroup'"
            )
            ->getResult();
    }
    public function findAllKidsnogroup()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e.id,e.nom,e.prenom,e.datenaiss,e.sexe FROM PlanBundle:Enfant e  where e.idGroup IS NULL "
            )
            ->getResult();
    }
    public function numberofkids($idGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT count(e.id) FROM PlanBundle:Enfant e  where e.idGroup='$idGroup' "
            )
            ->getResult();
    }
    public function deleteKids($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "Update PlanBundle:Enfant e set e.idGroup = NULL where  e.id ='$id'  "
            )
            ->getResult();
    }
    public function AjouterKids($idGroup,$id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "Update PlanBundle:Enfant e set e.idGroup ='$idGroup' where e.id='$id' "
            )
            ->getResult();
    }

    public function findgroupnom($idGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT g.nomGroup from PlanBundle:Groupe g where g.idGroup='$idGroup' "
            )
            ->getResult();
    }
    public function impByGroup($nomGroup)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT e.id,e.nom,e.prenom,e.datenaiss,e.sexe FROM PlanBundle:Enfant e  where e.idGroup =(SELECT g.idGroup From PlanBundle:Groupe g where  g.nomGroup='$nomGroup')"
            )
            ->getResult();
    }
    public function allgroups()
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT g.nomGroup from PlanBundle:Groupe g  "

            )
            ->getResult();
    }
}
